function s_poli5 = s_poli5(T,L,V0,V,A0,A)
%S_POLI5
%    S_POLI5 = S_POLI5(T,L,V0,V,A0,A)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jul-2019 20:34:53

t2 = T.^2;
t3 = A0.*t2.*3.0;
s_poli5 = [1.0./T.^5.*(L.*-1.2e1+T.*V.*6.0+T.*V0.*6.0-A.*t2+A0.*t2).*(-1.0./2.0);(1.0./T.^4.*(L.*-3.0e1+t3+T.*V.*1.4e1+T.*V0.*1.6e1-A.*t2.*2.0))./2.0;1.0./T.^3.*(L.*-2.0e1+t3+T.*V.*8.0+T.*V0.*1.2e1-A.*t2).*(-1.0./2.0);A0./2.0;V0];
