function invJ = invJ(in1)
%INVJ
%    INVJ = INVJ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2019 23:46:29

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = sin(q2);
t4 = 1.0./t3;
t5 = cos(t2);
t6 = sin(t2);
invJ = reshape([t4.*t5.*2.0,t4.*(t5+cos(q1)).*-2.0,t4.*t6.*2.0,t4.*(t6+sin(q1)).*-2.0],[2,2]);
