function M = M(in1)
%M
%    M = M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Oct-2019 23:46:38

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q2.*2.0;
t3 = cos(t2);
t4 = q1.*2.0;
t5 = t2+t4;
t6 = t3-1.0;
t7 = 1.0./t6;
t8 = sin(t5);
t9 = cos(t5);
t10 = t9.*3.0;
M = reshape([-t7.*(t3.*-3.0+t10+6.0),t7.*t8.*-3.0,t7.*t8.*-3.0,t7.*(t3.*3.0+t10-6.0)],[2,2]);
