function G = G(t,g,q1,q2,q3,m1,m2,m3,L1,L2,L3)
%G
%    G = G(T,G,Q1,Q2,Q3,M1,M2,M3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Nov-2019 23:00:26

t2 = sin(q1);
t3 = L1.*t2;
t4 = q1-q2;
t5 = sin(t4);
t6 = q1-q2+q3;
t7 = sin(t6);
t8 = (L3.*t7)./2.0;
t9 = L2.*t5;
G = [-g.*m2.*(t3+(L2.*t5)./2.0)-g.*m3.*(t3+t8+t9)-(L1.*g.*m1.*t2)./2.0;g.*m3.*(t8+t9)+(L2.*g.*m2.*t5)./2.0;L3.*g.*m3.*t7.*(-1.0./2.0)];
