function M = M(t,g,q1,q2,q3,m1,m2,m3,L1,L2,L3)
%M
%    M = M(T,G,Q1,Q2,Q3,M1,M2,M3,L1,L2,L3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    15-Nov-2019 23:00:26

t2 = L1.^2;
t3 = cos(q2);
t4 = L2.^2;
t5 = t4./4.0;
t6 = cos(q3);
t7 = L2.*L3.*t6;
t8 = L1.*L2.*t3;
t9 = L3.^2;
t10 = t9./4.0;
t11 = q2-q3;
t12 = cos(t11);
t13 = (L1.*L2.*t3)./2.0;
t14 = t5+t13;
t15 = (L1.*L3.*t12)./2.0;
t16 = t4+t7+t8+t10+t15;
t18 = m2.*t14;
t19 = m3.*t16;
t17 = -t18-t19;
t20 = L3.*3.0;
t21 = L2.*t6.*6.0;
M = reshape([(m1.*t2)./3.0+m2.*(t2+t5+t8)+m3.*(t2+t4+t7+t10+L1.*L2.*t3.*2.0+L1.*L3.*t12),t17,(L3.*m3.*(t20+t21+L1.*t12.*6.0))./1.2e1,t17,m2.*t4.*(7.0./1.2e1)+m3.*(t4+t7+t10),L3.*m3.*(t20+t21).*(-1.0./1.2e1),t17,-m3.*(t10+(L2.*L3.*t6)./2.0),m3.*t9.*(7.0./1.2e1)],[3,3]);
